### ISSUE TITLE
Milestones: add section for mental health practitioner/support services

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#175]

**Comment by FridahC** [comment]
Priority task

**Comment by eatyourpeas** [comment]
No problem
@coldunk @FridahC if possible please provide the label text, the reference text (NICE etc) for the extra fields.
- [ ] add new fields to data model
- [ ] add new help text for labels and reference text for popups to data model
- [ ] add POST request call backs to view
- [ ] update scores to form to update UI if incomplete

**Comment by eatyourpeas** [comment]
message from @nikyraja 
Please could we have the following questions:
‘Is there evidence of the child being assessed for mental health problems via clinical enquiry or the use of a screening questionnaire?’
Yes/No options
Add ‘Does the child have any mental health issue identified?’
Yes/No options
If ‘Yes’ is selected, have the following question appear:
(‘Add details of any known mental health problem(s)’, with the following options: ‘Mood Disorder, Anxiety, Emotional/behavioural, Self-harm, or Other’
This is currently covered in the Tab 4 Multitaxial diagnosis )
‘Is there evidence of the child receiving support for their mental health?’ with the following options: 'Yes', 'No - referred but not received', or 'No - not referred and not received'
We discussed placing this under treatment and care planning?

**Comment by eatyourpeas** [comment]
@nikyraja @coldunk @FridahC  Before going ahead with this can I ask if there is a reason the ‘Is there evidence of the child receiving support for their mental health?' question can't be a simple yes or no? Do we audit against whether they have been referred but not seen? A yes/no becomes a toggle button where as a 4-way option like that would probably need to be a dropdown which is clunky to complete and slows the user down. For all other questions we have tended to reduce to yes/no for this reason.

**Comment by coldunk** [comment]
The issue we have is that often children are referred but they are rejected or there is no destination service for them to be supported.  In MRI and EEG the issue is more around delay.  In mental health there is no service.  We trying to unpick this and ensure that children have issue looked for, identified, referred and then received.  It could be broken down into 
Has the child been referred for support for their mental health?
Is there evidence of the child receiving support for their mental health?
we could then report on percentage referred and percentage receiving support?
This would get us to the same place but maybe simply the question set?

**Comment by eatyourpeas** [comment]
Thank you @coldunk if that is ok I will do your second option? It also allows people to score that kids are getting help without having been referred which seems to me quite likely too? Can change later if you don't like.
